apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: health-ai-doctor-mobile-route
  namespace: health-pujiang
spec:
  http:
  - backends:
    - serviceName: health-ai-fe-mobile
      servicePort: 8000
    match:
      hosts:
      - pre.mobile.doctor.inf-health.cn
      paths:
      - /*
      - /logout
    name: frontend
    plugins:
    - config:
        bearer_only: false
        client_id: health-pujiang
        client_secret: Z9AOcxxCtjp2W12eXyn77rETkybKLaSM
        discovery: https://login.infly.cn/realms/inf-public/.well-known/openid-configuration
        introspection_endpoint_auth_method: client_secret_post
        realm: inf-public
        redirect_uri: http://pre.mobile.doctor.inf-health.cn/balabala
        scope: openid profile
        session:
          secret: EE1z9v0VFlJUmzejPNye8sRQ2mzFaRyhMegxEApUfTM=
      enable: true
      name: openid-connect
    - name: response-rewrite
      config:
        headers:
          set:
            location: /
        status_code: 302
        vars:
        - - status
          - ==
          - 500
        - - uri
          - ~~
          - balabala
      enable: true