apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: health-ai-doctor-pcweb-route
  namespace: health-pre
spec:
  http:
  - backends:
    - serviceName: health-knowledge-assistant-service
      servicePort: 8088
    match:
      hosts:
      - pre.pc.zhongshan-doctor.inf-health.cn
      paths:
      - "/api/doctor/*"
    name: backend
    plugins:
    - name: response-rewrite
      config:
        status_code: 401
        vars:
        - - status
          - ==
          - 302
        - - uri
          - '!'
          - ~~
          - balabala
      enable: true
  - backends:
    - serviceName: health-ai-fe
      servicePort: 8000
    match:
      hosts:
      - pre.pc.zhongshan-doctor.inf-health.cn
      paths:
      - /*
      - /logout
    name: frontend
    plugins:
    - config:
        bearer_only: false
        client_id: health-ai-doctor-pc-pre
        client_secret: OnY5UCKENyOpTEKiTVgtr0m3WDJtHFII
        discovery: https://login.infly.cn/realms/inf-public/.well-known/openid-configuration
        introspection_endpoint_auth_method: client_secret_post
        realm: inf-public
        redirect_uri: https://pre.pc.zhongshan-doctor.inf-health.cn/balabala
        scope: openid profile
        session:
          secret: EE1z9v0VFlJUmzejPNye8sRQ2mzFaRyhMegxEApUfTM=
      enable: true
      name: openid-connect
    - name: response-rewrite
      config:
        headers:
          set:
            location: /
        status_code: 302
        vars:
        - - status
          - ==
          - 500
        - - uri
          - ~~
          - balabala
      enable: true