apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: health-knowledge-assistant-route
  namespace: health-dev
spec:
  http:
  - backends:
    - serviceName: health-knowledge-assistant-service
      servicePort: 8088
    match:
      hosts:
      - dev.inf-health.work
      paths:
      - "/forward/api/*"
    name: "forward"
    priority: 10
    plugins:
    - name: "proxy-rewrite"
      enable: true
      config:
        regex_uri:
        - "^/forward/api/(.*)"
        - "/api/$1"
        headers:
          set:
            Client-Type: "forward"
  - backends:
    - serviceName: health-knowledge-assistant-service
      servicePort: 8088
    match:
      hosts:
      - dev.inf-health.work
      paths:
      - /knowledge-assistant/api/*
    name: backend
    plugins:
    - config:
        bearer_only: false
        client_id: health-knowledge-assistant-dev
        client_secret: er9BN8SF5SELCvT1sW0AJa9rrvb5Hdu5
        discovery: https://login.infly.cn/realms/inf-internal/.well-known/openid-configuration
        introspection_endpoint_auth_method: client_secret_post
        realm: inf-internal
        redirect_uri: http://dev.inf-health.work/knowledge-assistant/api/bababab
        scope: openid profile
        session:
          secret: EE1z9v0VFlJUmzejPNye8sRQ2mzFaRyhMegxEApUfTM=
      enable: true
      name: openid-connect
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
        - "^/knowledge-assistant/api/(.*)"
        - "/api/$1"
    - name: response-rewrite
      config:
        status_code: 401
        vars:
        - - status
          - ==
          - 302
        - - uri
          - '!'
          - ~~
          - bababab
      enable: true
  - backends:
    - serviceName: health-assistant-fe
      servicePort: 8000
    match:
      hosts:
      - dev.inf-health.work
      paths:
      - /knowledge-assistant
      - /knowledge-assistant/*
      - /logout
    name: frontend
    plugins:
    - config:
        bearer_only: false
        client_id: health-knowledge-assistant-dev
        client_secret: er9BN8SF5SELCvT1sW0AJa9rrvb5Hdu5
        discovery: https://login.infly.cn/realms/inf-internal/.well-known/openid-configuration
        introspection_endpoint_auth_method: client_secret_post
        realm: inf-internal
        redirect_uri: http://dev.inf-health.work/knowledge-assistant/api/bababab
        scope: openid profile
        session:
          secret: EE1z9v0VFlJUmzejPNye8sRQ2mzFaRyhMegxEApUfTM=
      enable: true
      name: openid-connect
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri:
        - "^/knowledge-assistant/(.*)"
        - "/$1"