# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ile_common.proto\x12\x0b\x66ile_common\"\x1c\n\rFileStageHint\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\xe7\x01\n\x08\x46ileMeta\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x63oll_key\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x04 \x01(\t\x12\x0c\n\x04mime\x18\x05 \x01(\t\x12\x0c\n\x04size\x18\x06 \x01(\x03\x12\x0b\n\x03md5\x18\x07 \x01(\t\x12%\n\x05stage\x18\x08 \x01(\x0e\x32\x16.file_common.FileStage\x12-\n\tstage_msg\x18\t \x01(\x0b\x32\x1a.file_common.FileStageHint\x12\x12\n\nis_deleted\x18\n \x01(\x08\x12\r\n\x05\x61ttrs\x18\x17 \x01(\t\"\x88\x01\n\nCollection\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x06 \x01(\t\x12+\n\nvisibility\x18\x07 \x01(\x0e\x32\x17.file_common.Visibility\x12\x12\n\ncreator_id\x18\x0b \x01(\t\x12\x10\n\x08owner_id\x18\x0c \x01(\t*>\n\nVisibility\x12\x0f\n\x0bVSB_NOTUSED\x10\x00\x12\x0f\n\x0bVSB_PRIVATE\x10\x01\x12\x0e\n\nVSB_PUBLIC\x10\x02*9\n\tFileStage\x12\x0c\n\x08\x46S_READY\x10\x00\x12\x10\n\x0c\x46S_PREUPLOAD\x10\x01\x12\x0c\n\x08\x46S_ERROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VISIBILITY']._serialized_start=437
  _globals['_VISIBILITY']._serialized_end=499
  _globals['_FILESTAGE']._serialized_start=501
  _globals['_FILESTAGE']._serialized_end=558
  _globals['_FILESTAGEHINT']._serialized_start=34
  _globals['_FILESTAGEHINT']._serialized_end=62
  _globals['_FILEMETA']._serialized_start=65
  _globals['_FILEMETA']._serialized_end=296
  _globals['_COLLECTION']._serialized_start=299
  _globals['_COLLECTION']._serialized_end=435
# @@protoc_insertion_point(module_scope)
