# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: knowledge_doc_online_dump.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fknowledge_doc_online_dump.proto\x12\x19knowledge_doc_online_dump\"\x18\n\tStageHint\x12\x0b\n\x03msg\x18\x01 \x01(\t\".\n\x0bLaunchParam\x12\x10\n\x08\x66ile_key\x18\x01 \x01(\t\x12\r\n\x05\x61ttrs\x18\x02 \x01(\t\"\xd2\x02\n\x11\x44ocOnlineDumpTask\x12\x0e\n\x06kb_key\x18\x01 \x01(\t\x12\x0f\n\x07\x64oc_key\x18\x02 \x01(\t\x12/\n\x05stage\x18\x08 \x01(\x0e\x32 .knowledge_doc_online_dump.Stage\x12\x38\n\nstage_hint\x18\t \x01(\x0b\x32$.knowledge_doc_online_dump.StageHint\x12:\n\x0bimport_type\x18\n \x01(\x0e\x32%.knowledge_doc_online_dump.ImportType\x12\x14\n\x0craw_file_key\x18\x0f \x01(\t\x12\x16\n\x0eparsed_doc_key\x18\x10 \x01(\t\x12\x16\n\x0esearch_doc_key\x18\x11 \x01(\t\x12\r\n\x05title\x18\x12 \x01(\t\x12\r\n\x05\x61ttrs\x18\x17 \x01(\t\x12\x11\n\tcreate_ts\x18\x1e \x01(\x03*\x98\x01\n\x05Stage\x12\r\n\tSTG_ERROR\x10\x00\x12\r\n\tSTG_READY\x10\x01\x12\x0f\n\x0bSTG_PREPARE\x10\x02\x12\r\n\tSTG_PARSE\x10\x03\x12\r\n\tSTG_CHUNK\x10\x04\x12\x0e\n\nSTG_ADDDOC\x10\x05\x12\x0e\n\nSTG_DELETE\x10\n\x12\x0f\n\x0bSTG_DELETED\x10\x0b\x12\x11\n\rSTG_DELETEERR\x10\x0c*.\n\nImportType\x12\x0e\n\nIT_RAWFILE\x10\x00\x12\x10\n\x0cIT_PARSEDDOC\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'knowledge_doc_online_dump_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STAGE']._serialized_start=478
  _globals['_STAGE']._serialized_end=630
  _globals['_IMPORTTYPE']._serialized_start=632
  _globals['_IMPORTTYPE']._serialized_end=678
  _globals['_STAGEHINT']._serialized_start=62
  _globals['_STAGEHINT']._serialized_end=86
  _globals['_LAUNCHPARAM']._serialized_start=88
  _globals['_LAUNCHPARAM']._serialized_end=134
  _globals['_DOCONLINEDUMPTASK']._serialized_start=137
  _globals['_DOCONLINEDUMPTASK']._serialized_end=475
# @@protoc_insertion_point(module_scope)
